import Head from "next/head";

import {
  Layout,
  LayoutHeader,
  LayoutHero,
  LayoutHeroBackground,
  LayoutSidebar,
  LayoutMain,
  LayoutFooter,
  LayoutContainer,
} from "../components/Layout";

import Container from "../components/Container";
import LayoutSidebarHeader from "../components/Layout/LayoutSidebarHeader.styled";
import LayoutSidebarBody from "../components/Layout/LayoutSidebarBody.styled";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <LayoutHeader>
          <Container></Container>
        </LayoutHeader>

        <LayoutHero>
          <LayoutHeroBackground></LayoutHeroBackground>
          <LayoutContainer></LayoutContainer>
        </LayoutHero>

        <LayoutSidebar>
          <LayoutSidebarHeader></LayoutSidebarHeader>
          <LayoutSidebarBody></LayoutSidebarBody>
        </LayoutSidebar>

        <LayoutMain>
          <LayoutContainer></LayoutContainer>
        </LayoutMain>

        <LayoutFooter>
          <Container></Container>
        </LayoutFooter>
      </Layout>
    </div>
  );
}
