import Head from "next/head";

import {
  Layout,
  LayoutHeader,
  LayoutHero,
  LayoutHeroBackground,
  LayoutSidebar,
  LayoutMain,
  LayoutFooter,
  LayoutContainer,
} from "../components/Layout";

import Container from "../components/Container";
import SidebarHeader from "../components/SidebarHeader.styled";
import SidebarBody from "../components/SidebarBody.styled";

import { createClient } from "../prismic";
import { PrismicImage, PrismicRichText } from "@prismicio/react";

export async function getStaticProps({ previewData }) {
  const client = createClient({ previewData });
  const page = await client.getByUID("home", "home");
  return { props: { page } };
}

export default function Home({ page }) {
  console.log(page);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <LayoutHeader>
          <Container>
            <img width="30px" src={"/favicon.ico"}></img>Visionautik Akademie
          </Container>
        </LayoutHeader>

        <LayoutHero>
          <LayoutHeroBackground>
            <PrismicImage
              style={{ height: "100%", width: "100%", objectFit: "cover" }}
              field={page.data.heroImage}
            ></PrismicImage>
          </LayoutHeroBackground>
          <LayoutContainer>
            <PrismicRichText field={page.data.heroText}></PrismicRichText>
          </LayoutContainer>
        </LayoutHero>

        <LayoutSidebar>
          <SidebarHeader>top</SidebarHeader>
          <SidebarBody>bottom</SidebarBody>
        </LayoutSidebar>

        <LayoutMain>
          <LayoutContainer>
            <PrismicRichText field={page.data.bodyText}></PrismicRichText>
          </LayoutContainer>
        </LayoutMain>

        <LayoutFooter>
          <Container></Container>
        </LayoutFooter>
      </Layout>
    </div>
  );
}
